- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: install apache
    yum:
        name: httpd
        state: present

  - name: start httpd
    service:
        name: httpd
        state: started    

  - name: copy master to slave
    copy:
        src: /home/ec2-user/index.html
        dest: /var/www/html
        mode: '777'       
